services:
  discord-twitch-notify:
    # image: ghcr.io/trojanerhd/discord-twitch-notify:latest
    # Build the container locally
    build: .
    env_file: .env
    volumes:
      - ./store.json:/usr/src/trojaner/store.json
      - discord-twitch-notify:/usr/src/trojaner
    # Simple port forwarding
    # ports:
      # - "3334:80"

volumes:
  discord-twitch-notify:
